// models/LabRequest.js
import mongoose from 'mongoose'

const labRequestSchema = new mongoose.Schema({
  // Reference fields
  patient: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: [true, 'Patient is required']
  },
  doctor: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: [true, 'Doctor is required']
  },
  appointment: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Appointment'
  },
  session: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Session'
  },
  assignedTo: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User', // Lab personnel
    default: null
  },

  // Request details
  // ✅ FIX Bug 1 & 2:
  //   • Removed `required: true` — the field is generated by the pre('validate')
  //     hook below. Mongoose runs validation AFTER pre('validate') but BEFORE
  //     pre('save'), so using pre('validate') guarantees the value is present
  //     when the required check runs.
  //   • Removed `countDocuments()` — not atomic; concurrent saves produced
  //     duplicate numbers that collided on the unique index and caused a silent
  //     500. Replaced with timestamp + 4-digit random suffix (collision-safe).
  requestNumber: {
    type: String,
    unique: true
  },

  tests: [{
    testName: {
      type: String,
      required: true
    },
    testCode: String,
    category: {
      type: String,
      enum: [
        'Hematology',
        'Biochemistry',
        'Chemistry',      // alias used by the frontend commonLabTests list
        'Microbiology',
        'Immunology',
        'Pathology',
        'Radiology',
        'Imaging',        // used by the frontend for X-Ray, Ultrasound, CT, MRI
        'Serology',       // used by the frontend for HIV, Hepatitis, Malaria, Typhoid
        'Molecular Biology',
        'Other'
      ]
    },
    instructions: String,
    specimenType: String, // Blood, Urine, Tissue, etc.
    collectionDate: Date,
    status: {
      type: String,
      enum: ['pending', 'collected', 'processing', 'completed'],
      default: 'pending'
    }
  }],

  // Priority and status
  priority: {
    type: String,
    enum: ['routine', 'urgent', 'stat', 'emergency'],
    default: 'routine'
  },
  status: {
    type: String,
    enum: ['pending', 'assigned', 'specimen_collected', 'processing', 'results_uploaded', 'completed', 'cancelled', 'rejected'],
    default: 'pending'
  },

  // Clinical information
  clinicalNotes: String,
  provisionalDiagnosis: String,

  // Results
  results: [{
    testName: String,
    testCode: String,
    result: String,
    normalRange: String,
    unit: String,
    flag: {
      type: String,
      enum: ['normal', 'high', 'low', 'critical', 'abnormal'],
      default: 'normal'
    },
    performedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    performedAt: Date,
    verifiedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    verifiedAt: Date,
    notes: String
  }],

  // Attachments (PDF reports, images, scans)
  attachments: [{
    fileName: String,
    fileUrl: String,
    fileType: String,
    uploadedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    uploadedAt: {
      type: Date,
      default: Date.now
    },
    description: String
  }],

  // Comments and communication
  comments: [{
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    text: String,
    timestamp: {
      type: Date,
      default: Date.now
    },
    type: {
      type: String,
      enum: ['note', 'query', 'clarification', 'rejection_reason'],
      default: 'note'
    }
  }],

  // Billing
  paymentRequired: {
    type: Boolean,
    default: true
  },
  estimatedCost: Number,
  actualCost: Number,
  paymentStatus: {
    type: String,
    enum: ['pending', 'partial', 'paid', 'waived'],
    default: 'pending'
  },

  // Timestamps
  requestedAt: {
    type: Date,
    default: Date.now
  },
  assignedAt: Date,
  specimenCollectedAt: Date,
  processingStartedAt: Date,
  completedAt: Date,
  reportedAt: Date,

  // ✅ FIX Bug 3: Declare resultsUploadedAt explicitly so Mongoose does not
  //    silently drop the value set in labController.uploadLabResults().
  //    finalizeMedicalRecord() relies on this field when snapshotting results.
  resultsUploadedAt: {
    type: Date,
    default: null
  },

  // Quality control
  qcStatus: {
    type: String,
    enum: ['pending', 'passed', 'failed', 'review_required'],
    default: 'pending'
  },
  qcNotes: String,

  // Rejection info
  rejectionReason: String,
  rejectedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  rejectedAt: Date
}, {
  timestamps: true
})

// Indexes for efficient queries
labRequestSchema.index({ patient: 1, createdAt: -1 })
labRequestSchema.index({ doctor: 1, createdAt: -1 })
labRequestSchema.index({ assignedTo: 1, status: 1 })
labRequestSchema.index({ status: 1, priority: -1 })

// ── Pre-validate hook: generate a collision-safe request number ───────────────
// ✅ FIX Bug 1: Use pre('validate') instead of pre('save').
//
//   Execution order in Mongoose:
//     pre('validate') → validation (required check) → pre('save') → DB write
//
//   The old pre('save') hook ran AFTER validation, so `requestNumber` was
//   still undefined when the `required: true` check fired → ValidationError.
//   Moving to pre('validate') ensures the number is set before validation runs.
//
// ✅ FIX Bug 2: Use timestamp + random suffix instead of countDocuments().
//
//   countDocuments() is not atomic — two concurrent saves read the same count
//   and both try to write the same requestNumber, hitting the unique index and
//   throwing a duplicate-key error. The timestamp+random approach is safe:
//     • Date.now() → 13-digit ms timestamp, unique per process tick
//     • 4-digit random suffix → collision-safe for same-millisecond saves
//   Result format: LAB<YYYY><MM><ms><rand>  e.g. LAB20260314171123456789012
labRequestSchema.pre('validate', function (next) {
  if (!this.requestNumber) {
    const date  = new Date()
    const year  = date.getFullYear()
    const month = String(date.getMonth() + 1).padStart(2, '0')
    const ms    = Date.now().toString()                              // 13 digits
    const rand  = String(Math.floor(Math.random() * 9000) + 1000)  // 4 digits
    this.requestNumber = `LAB${year}${month}${ms}${rand}`
  }
  next()
})

// Method to check if all tests are completed
labRequestSchema.methods.areAllTestsCompleted = function () {
  return this.tests.every(test => test.status === 'completed')
}

// Method to check if any test is critical
labRequestSchema.methods.hasCriticalResults = function () {
  return this.results.some(result => result.flag === 'critical')
}

const LabRequest = mongoose.model('LabRequest', labRequestSchema)

export default LabRequest